org/website-org/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Represents an item we are keeping track of to display on our public-facing website.</description>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Resource Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

org/website-org/main/default/objects/Resource__c/fields/Canonical_URL__c.field-meta.xml
<CustomField>
    <fullName>Canonical_URL__c</fullName>
    <description>The official URL for this resource.</description>
    <externalId>true</externalId>
    <inlineHelpText>The official URL for this resource.</inlineHelpText>
    <label>Canonical URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

org/website-org/main/default/classes/AutoIndex.cls
/**
 * Simple scheduled Apex class that fetches the open-force public repositories and adds them to our Resources object.
 */
public with sharing class AutoIndex implements Schedulable {

	public void execute(SchedulableContext sc) {

		fetchRepositories();
	}

	@Future(Callout=true)
	public static void fetchRepositories() {

		// set up an API call to Github
		HttpRequest req = new HttpRequest();
		req.setEndpoint('https://api.github.com/orgs/open-force/repos');
		req.setTimeout(120000);
		req.setMethod('GET');

		// Call the Github API to fetch information about open-force repositories
		JSONParse repos = new JSONParse(new Http().send(req).getBody());

		// Iterate through the repos we found and make sure we have a Resource created for each one
		List<Resource__c> resourcesToUpsert = new List<Resource__c>();
		for(JSONParse repo : repos.asList()) {
			resourcesToUpsert.add(new Resource__c(
				Canonical_URL__c = repo.get('html_url').getStringValue()
			));
		}
		upsert resourcesToUpsert Resource__c.Canonical_URL__c;
	}
}